package style

import "github.com/charmbracelet/lipgloss"

const (
	black     = lipgloss.Color("#000000")
	blue      = lipgloss.Color("6")
	pink      = lipgloss.Color("#E760FC")
	darkred   = lipgloss.Color("#FF0000")
	darkgreen = lipgloss.Color("#00FF00")
	grey      = lipgloss.Color("#737373")
	red       = lipgloss.Color("#FF5353")
	softwhite = lipgloss.Color("7")
	yellow    = lipgloss.Color("#DBBD70")
	white     = lipgloss.Color("#FFFFFF")
)

var (
	Regular                    = lipgloss.NewStyle()
	Bold                       = Regular.Copy().Bold(true)
	Logo                       = Regular.Copy().Padding(0, 1).Foreground(yellow)
	ClusterUrl                 = Bold.Copy()
	KeyHelp                    = Regular.Copy().Padding(0, 2)
	KeyHelpKey                 = Regular.Copy().Foreground(blue).Bold(true)
	KeyHelpDescription         = Regular.Copy().Foreground(softwhite)
	Header                     = Regular.Copy().Padding(0, 1).Border(lipgloss.RoundedBorder(), true)
	JobRowPending              = Regular.Copy().Foreground(yellow)
	JobRowDead                 = Regular.Copy().Foreground(red)
	PseudoPrompt               = Regular.Copy().Background(blue)
	Viewport                   = Regular.Copy().Background(black)
	ViewportHeaderStyle        = Bold.Copy()
	ViewportSelectedRowStyle   = Regular.Copy().Foreground(black).Background(blue)
	ViewportHighlightStyle     = Regular.Copy().Foreground(black).Background(pink)
	ViewportFooterStyle        = Regular.Copy().Foreground(grey)
	SaveDialogPromptStyle      = Regular.Copy().Background(darkred).Foreground(black)
	SaveDialogPlaceholderStyle = Regular.Copy().Background(darkred).Foreground(black)
	SaveDialogTextStyle        = Regular.Copy().Background(darkred).Foreground(black)
	StdOut                     = Regular.Copy().Foreground(white)
	StdErr                     = Regular.Copy().Foreground(red)
	SuccessToast               = Bold.Copy().PaddingLeft(1).Foreground(black).Background(darkgreen)
	ErrorToast                 = Bold.Copy().PaddingLeft(1).Foreground(black).Background(darkred)
)
