# .goreleaser.yml file
# https://github.com/robinovitch61/wander/
# Documentation at http://goreleaser.com
#
# Thanks to @neomantra for setup work on this https://github.com/robinovitch61/wander/issues/33

project_name: wander

before:
  hooks:
    - go mod tidy

builds:
  - binary: wander
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/robinovitch61/wander/cmd.Version=v{{ .Version }} -X github.com/robinovitch61/wander/cmd.CommitSHA={{ .Commit }}
    goos:
      - darwin
      - freebsd
      - linux
      - windows

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

release:
  github:
    owner: robinovitch61
    name: wander

brews:
  - homepage: https://github.com/robinovitch61/wander
    description: "A terminal app for Nomad by HashiCorp"
    folder: Formula
    tap:
      owner: robinovitch61
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@theleo.zone
    install: |
      bin.install "wander"
